# Enables/disable deployment.
# For a web app enable a deployment.
deployment:
  enabled: false

image:
  repository:
  tag:

command:
  - bundle
args:
  - exec
  - rails
  - server

envs: []
port:

serviceAccount:
  enabled: true
  annotations: {}
  name:

resourceRequests: {}
resourceLimits: {}

replicas:
  autoscalingEnabled: false
  replicaCount:
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

# Service port for internal communication
svcPort: 80

ingress:
  annotations: {}
  enabled: false
  className:
  host:
  path:

commonLabels: {}

# Pod Config
pod:
  annotations: {}

# Job Setup
job:
  enabled: false
  command:
    - bundle
    - exec
  args:
    - rake
    - -T

cron_job:
  enabled: false
  command:
    - bundle
    - exec
  args:
    - rake
    - -T

